services:
  postgres:
    image: postgres:16-alpine
    container_name: where-to-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: whereto
      POSTGRES_PASSWORD: whereto
      POSTGRES_DB: where_to
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
